AUGMENTATION: True
IMAGE_SIZE: [224, 224,3]  # as per base model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 5
CLASSES: 2  #coccidiosis and healthy
WEIGHTS: "imagenet"  
LEARNING_RATE: 0.01
OPTIMIZER: "adam"
LOSS: "categorical_crossentropy"